(() => {
  const $ = (s) => document.querySelector(s);
  const intro = $('#intro'), scene = $('#envelopeScene'), open = $('#openInvitation');
  const music = $('#music'), musicToggle = $('#musicToggle'), particles = $('#particles');
  let opened = false;
  const makeParticles = () => { for (let i = 0; i < 34; i++) { const p = document.createElement('i'); p.className = 'particle'; const a = Math.random() * Math.PI * 2, d = 90 + Math.random() * 250; p.style.setProperty('--x', `${Math.cos(a) * d}px`); p.style.setProperty('--y', `${Math.sin(a) * d}px`); p.style.animationDelay = `${Math.random() * .18}s`; particles.append(p); setTimeout(() => p.remove(), 1500); } };
  function openInvite() { if (opened) return; opened = true; scene.classList.add('open'); makeParticles(); music.volume = .55; music.play().catch(() => {}); musicToggle.classList.add('show'); setTimeout(() => intro.classList.add('open'), 1120); }
  open.addEventListener('click', openInvite); open.addEventListener('keydown', e => { if (e.key === 'Enter' || e.key === ' ') openInvite(); });
  musicToggle.addEventListener('click', () => { if (music.paused) { music.play(); musicToggle.setAttribute('aria-label', 'Pause background music'); musicToggle.setAttribute('aria-pressed', 'false'); } else { music.pause(); musicToggle.setAttribute('aria-label', 'Play background music'); musicToggle.setAttribute('aria-pressed', 'true'); } });
  const target = new Date('2026-12-31T11:00:00+05:30').getTime();
  function tick() { const n = Math.max(0, target - Date.now()), values = [Math.floor(n / 864e5), Math.floor(n / 36e5) % 24, Math.floor(n / 6e4) % 60, Math.floor(n / 1e3) % 60]; ['days','hours','minutes','seconds'].forEach((id, i) => $(`#${id}`).textContent = String(values[i]).padStart(2, '0')); }
  tick(); setInterval(tick, 1000);
  const canvas = $('#scratchCard'), ctx = canvas.getContext('2d'); let drawing = false, revealed = false;
  function sizeCanvas() { const r = canvas.getBoundingClientRect(), dpr = devicePixelRatio || 1; canvas.width = r.width * dpr; canvas.height = r.height * dpr; ctx.setTransform(dpr, 0, 0, dpr, 0, 0); const g = ctx.createLinearGradient(0,0,r.width,r.height); g.addColorStop(0,'#856229'); g.addColorStop(.5,'#e6c77f'); g.addColorStop(1,'#9a7131'); ctx.fillStyle = g; ctx.fillRect(0,0,r.width,r.height); ctx.fillStyle = '#fffaf1'; ctx.font = '600 12px Poppins'; ctx.textAlign = 'center'; ctx.fillText('SCRATCH TO REVEAL', r.width/2, r.height/2+4); }
  function scratch(e) { if (!drawing || revealed) return; e.preventDefault(); const r = canvas.getBoundingClientRect(), p = e.touches ? e.touches[0] : e; ctx.globalCompositeOperation = 'destination-out'; ctx.beginPath(); ctx.arc(p.clientX-r.left,p.clientY-r.top,27,0,Math.PI*2); ctx.fill(); }
  function finish() { drawing = false; const pixels = ctx.getImageData(0,0,canvas.width,canvas.height).data; let clear = 0, total = 0; for (let i=3;i<pixels.length;i+=80) { total++; if (!pixels[i]) clear++; } if (clear/total > .6) { revealed = true; canvas.style.transition = 'opacity .55s'; canvas.style.opacity = 0; setTimeout(() => canvas.style.display = 'none', 560); } }
  canvas.addEventListener('pointerdown', e => { drawing = true; canvas.setPointerCapture(e.pointerId); scratch(e); }); canvas.addEventListener('pointermove', scratch); canvas.addEventListener('pointerup', finish); canvas.addEventListener('pointerleave', finish); sizeCanvas(); addEventListener('resize', () => !revealed && sizeCanvas());
  const observer = new IntersectionObserver(entries => entries.forEach(e => { if (e.isIntersecting) { e.target.classList.add('in-view'); observer.unobserve(e.target); } }), {threshold:.17}); document.querySelectorAll('.reveal').forEach(e => observer.observe(e));
  const track = $('#galleryTrack'); let down = false, start = 0, scroll = 0, auto; const stopAuto = () => clearInterval(auto); const startAuto = () => { stopAuto(); auto = setInterval(() => { if (!down) track.scrollBy({left: track.clientWidth*.55, behavior:'smooth'}); }, 4300); }; track.addEventListener('pointerdown', e => { down=true; start=e.clientX; scroll=track.scrollLeft; stopAuto(); }); track.addEventListener('pointermove', e => { if (down) track.scrollLeft = scroll-(e.clientX-start); }); ['pointerup','pointerleave'].forEach(t => track.addEventListener(t, () => { down=false; startAuto(); })); startAuto();
  $('#shareInvitation').addEventListener('click', async e => { e.preventDefault(); const data={title:'Albert ♡ Neena | Wedding Invitation',text:'You are warmly invited to celebrate Albert and Neena.',url:location.href.split('#')[0]}; try { if (navigator.share) await navigator.share(data); else { await navigator.clipboard.writeText(data.url); e.currentTarget.textContent='Link copied'; setTimeout(()=>e.currentTarget.textContent='Share this invitation',1600); } } catch {} });
})();
